version: '3.8'
services:
  temporal:
    image: temporalio/auto-setup:1.24.2
    ports:
      - "7233:7233"  # gRPC
      - "8233:8233"  # UI
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
    depends_on:
      - postgresql

  postgresql:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    ports:
      - "5433:5432"
    volumes:
      - temporal-db:/var/lib/postgresql/data

  temporal-ui:
    image: temporalio/ui:2.26.2
    ports:
      - "8888:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233

volumes:
  temporal-db:
